---
settings:
  color: 80e5ff
keywords: 
  -
    name: 'forward'
    short: 'fd'
    description: "Gehe 10 Schritte vorwärts"
    example: "fd 10"
  -
    name: 'back'
    short: 'bk'
    description: "Gehe 10 Schritte rückwärts"
    example: "bk 10"
  -
    name: 'left'
    short: "lt"
    description: "Drehe dich um 90 Grad nach links"
    example: "lt 90"
  -
    name: "right"
    short: "rt"
    description: "Drehe dich um 45 Grad nach rechts"
    example: "rt 45"
  -
    name: "clearscreen"
    short: "cs"
    description: "Lösche alles, was du bisher gezeichnet hast"
    example: "cs"
  -
    name: 'setpencolor'
    short: "setpc"
    description: "Nutze einen roten Stift"
    example: "setpc 1"
  -
    name: "penup"
    short: "pu"
    description: "Laufe ohne zu zeichnen"
    example: "pu"
  -
    name: 'pendown'
    short: "pd"
    description: "Zeichne ab jetzt wieder"
    example: "pd"
  -
    name: 'hideturtle'
    short: "ht"
    description: "Verstecke dich"
    example: "ht"
  -
    name: 'showturtle'
    short: 'st'
    description: "Zeige dich"
    example: "st"
  -
    name: "repeat"
    description: "Wiederhole alles was in der Klammer steht 20 Mal"
    example: "repeat 20 [ ... ]"
  -
    name: "to"
    description: "Erstelle ein Programm mit dem Namen quadrat"
    example: "to quadrat ... end"
worksheets:
  -
    label: quadrat
  -
    label: dach
  -
    label: kreis
  -
    label: halbkreis
  - 
    label: kreuz
  -
    name: Stern 1
    label: stern
  -
    label: treppe
  - 
    label: schnecke
  -
    name: Quadrat
    label: quadratEinfach 
  -
    label: ausfuellen
    name: ausgefülltes Quadrat
  -
    label: quadratFarbig
    name: farbiges Quadrat
  -
    label: farbigesAchteck
    name: farbiges Achteck
  -
    label: linieGestrichelt
    name: gestrichelte Linie
  -
    label: stern2
    name: Stern 2
  -
    label: treppeLuecke
    name: lückenhafte Treppe
  -
    label: blume
    name: Blume 1
    color: df80ff
  -
    label: blume2
    name: Blume 2
    color: df80ff
  -
    label: blumeZweifarbig
    name: zweifarbige Blume
    color: df80ff
  -
    label: dreiQuadrate
    name: drei Quadrate
    color: df80ff
  -
    label: reifen
    color: df80ff
  - 
    label: mandala
    color: df80ff

